### ISSUE TITLE
開始測試自動更新

### ISSUE THREAD

**Issue by kiang** [kiang/1999.tainan.gov.tw#10]
程式是 https://github.com/kiang/1999.tainan.gov.tw/blob/master/bin/cron.php

現在放了一台機器每小時更新一次，每次更新 20 天的資料

**Comment by s890081tonyhsu** [comment]
umm，真的要拿這repo當更新用的基地嗎....
我比較建議另外開一個repo來處理會比較好

**Comment by kiang** [comment]
恩，我把程式轉到 https://github.com/kiang/1999.tainan.gov.tw_datasets 去了
