### ISSUE TITLE
在測試 ServiceAddRequest 時 server 吐 HTTP status code 500

### ISSUE THREAD

**Issue by newmanchen** [kiang/1999.tainan.gov.tw#12]
@kiang 我看你有次的 commit 也有遇到同樣的問題
但後來你有解決嗎?

後來還有個 commit 是送中文的名字 才解決的嗎?
同個 commit 裡面還有 + device_id 這個是必要的嗎? 從 API 看來是非必要

**Comment by newmanchen** [comment]
我暫時把照片拿掉後
就可以傳上去了

**Comment by kiang** [comment]
之前是 name 欄位不能放非中文，還沒遇過圖片問題
