### ISSUE TITLE
從上星期五下午開始 網站不是回傳0筆資料就是連不上

### ISSUE THREAD

**Issue by newmanchen** [kiang/1999.tainan.gov.tw#16]
你們也有遇到同樣的問題嗎?
我有寄信問市府窗口 但周末放假還沒回應

**Comment by kiang** [comment]
一樣的情況，星期五下午 5 點之後主機就昏迷不醒了，也是有回報但大概只能等星期一回應

**Comment by kiang** [comment]
看起來主機復活了，但程式有問題...

查詢結果的最後一筆資料少了結束標籤 < /record > ，這會導致解析器錯誤

**Comment by newmanchen** [comment]
目前回來的資料沒有異常

**Comment by kiang** [comment]
我現在還是無法取得正確的資料耶？原本的程式直接傳回 500 error 了

**Comment by newmanchen** [comment]
我用 app 連過去, 回來資料也都有正常顯示

**Comment by newmanchen** [comment]
你的 port 一樣用 82 嗎?
之前有一度改用  80 但後來市府的聯絡窗口有告知會改回 82

**Comment by newmanchen** [comment]
我看你的 port 也設定在 82..

**Comment by kiang** [comment]
80 or 82 都有試，其實你直接開 http://open1999.tainan.gov.tw:82/ServiceRequestsQuery.aspx 看到的就是錯誤訊息了，理論上應該傳回 xml 提示需要參數

**Comment by kiang** [comment]
找到問題了，因為一次拉太多資料...

原本是一次拉 20 天的資料，改成只拉 10 天，這機器有點弱...
