### ISSUE TITLE
以 js 改寫 request.php

### ISSUE THREAD

**Issue by kiang** [kiang/1999.tainan.gov.tw#4]
api 的說明可以參考 http://1999.tainan.gov.tw/OpenExplain.aspx

request.php 其實只有組合出像下面這樣一個 xml

```
<?xml version="1.0" encoding="UTF-8"?>
<root><city_id><![CDATA[tainan.gov.tw]]></city_id><area><![CDATA[北區]]></area><address_string><![CDATA[開元路與勝利路交叉口]]></address_string><lat><![CDATA[23.0066994]]></lat><long><![CDATA[120.2184427]]></long><email><![CDATA[nobody@example.com]]></email><device_id><![CDATA[well?]]></device_id><name><![CDATA[沒有人]]></name><phone><![CDATA[0800092000]]></phone><service_name><![CDATA[髒亂及汙染]]></service_name><subproject><![CDATA[其他汙染舉發]]></subproject><servicedescription><![CDATA[這是個測試，請忽略]]></servicedescription><description><![CDATA[這是個測試，請忽略]]></description><pictures><picture><description><![CDATA[這是 api 測試]]></description><fileName><![CDATA[hello.jpg]]></fileName><file>

...把檔案用 base64 轉換成文字

</file></picture></pictures></root>
```

然後以 POST 送到 http://open1999.tainan.gov.tw:82/ServiceRequestAdd.aspx

傳回結果像這樣：

```
<?xml version="1.0" encoding="utf-8"?><root>   <returncode>0</returncode>   <token>0</token>   <count>1</count>   <service_request_id><![CDATA[UN201505040115]]></service_request_id>   <service_notice></service_notice></root>
```

然後就算成功，目前可以在下面網址看到：
http://1999.tainan.gov.tw/OpenCaseShow.aspx?FSerialNumber=UN201505040115

可以直接看到是系統 bug ，理論上是立案成功才會公開，這個問題已經回報給開發單位

**Comment by s890081tonyhsu** [comment]
請幫我驗證一下下面的欄位型別是否正確，因為我可能連表單也會弄出來

## 地區選擇
- city_id：城市識別碼 → 給定一個清單，選一城市
- area：行政區 → 用js找出對應並塞入對應清單，選擇一項行政區

## 位置選擇

> 以下三點考慮用Google Map呈現，不過後來再決定
- address_string：地點 → 給定一欄位，輸入地點
- lat：緯度(WGS84)  → 給定一欄位，輸入緯度
- long：經度(WGS84)  → 給定一欄位，輸入經度

## 基本資料
- email：E-MAIL → 給定一欄位，輸入E-Mail
- device_id：僅用於行動裝置 → js偵測行動裝置，不過目前不知會有哪些結果
- name：姓名 → 給定一欄位，輸入姓名
- phone：電話 → 給定一欄位，輸入電話
- service_name：案件類型 → 給定清單，選擇一項案件類型
- subproject：案件事項 → 用js找出對應並塞入對應清單，選擇一項案件類型
- description：給定一多行欄位，輸入案件內容

## pictures：上傳照片

> 以下三點會搭配FileUpload (HTML5檔案工具)弄成三個上傳欄位
- description：照片描述
- fileName：檔案名稱
- file：檔案資料

待會我會先commit直接從php翻譯過來的js內容，不過要搭配一些js套件使用(我會弄個html方便測試)

**Comment by kiang** [comment]
- city_id 目前只有 "tainan.gov.tw" ，所以可以作為隱藏欄位直接送出
- area, address_string, lat & long 其實都可以透過 google map geocoding api 直接取得民眾所在地的資訊，只是因為不一定準確，也許第一時間自動填入後還可以保留做後續編輯
- lat & long 理論上可以透過地圖的點選取得，而不是讓民眾直接輸入(不過這兩個欄位也許會有進階使用者想要)
- service_name & subproject -> http://1999.tainan.gov.tw/%E9%A1%9E%E5%9E%8B%E5%8F%8A%E4%BA%8B%E9%A0%85%E7%9A%84%E9%97%9C%E8%81%AF.xls
- 照片最多三個

**Comment by s890081tonyhsu** [comment]
umm，我想確認一件事情

我js版本寫完了，不過在用ajax送資料的時候發生No-Access-Allow-Origin的問題，我想確認Server端是否有開放這東西，不然我只能單純產生資料而已

php沒有ajax，你用的方法沒有這問題，但javascript它講求這東西（跟瀏覽器有關），否則還是得弄一台機器處理。

**Comment by kiang** [comment]
恩，我想伺服器端應該連 Allow-Origin 是什麼都不知道 XD ，我可以試著把問題反應給官方，看看他們是否願意修正，真的不行就只能放個代理程式處理了

**Comment by s890081tonyhsu** [comment]
那我先把目前進度先commit上去，應該會是你目前的結果了

除了ajax不通之外，基本上都是從你的php檔硬轉過來XD

然後我刻意留下jpg轉base64個功能，用在未來產生表單使用

**Comment by kiang** [comment]
那就先關掉這個 issue 了 ref: 75b8384d149c0075684290012baf3a0b80ab9465
